* initial plan
** DONE setup windows 10 tech preview in virtualbox
   CLOSED: [2015-02-15 Sun 17:17]
It dies on April 15th
** DONE install Logitech Gaming software in win10
   CLOSED: [2015-02-15 Sun 17:18]
** DONE install usb logging software
   CLOSED: [2015-02-15 Sun 17:18]
installed:
usbmon
vusb-analyzer
** DONE try Logitech Gaming software in win10
   CLOSED: [2015-02-15 Sun 17:20]
Okay it works, but I have to go to menu:devices=>usb devics=>g600
When i do this, it takes over the mouse and I need a second mouse to use in linux during the takeover
** DONE try using usbmon / vusb-analyzer
   CLOSED: [2015-02-15 Sun 18:12]
usbmon ASCII capture
  sudo mount -t debugfs none_debugs /sys/kernel/debug
  sudo modprobe usbmon
  sudo ls /sys/kernel/debug/usb/usbmon/               
> 0s  0u	1s  1t	1u  2s	2t  2u	3s  3t	3u  4s	4t  4u
  lsusb | grep -i g600
> Bus 003 Device 002: ID 046d:c24a Logitech, Inc. G600 Gaming Mouse
  sudo cat /sys/kernel/debug/usb/devices
> ...
> T:  Bus=03 Lev=01 Prnt=01 Port=03 Cnt=01 Dev#=  2 Spd=12   MxCh= 0
> D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=32 #Cfgs=  1
> P:  Vendor=046d ProdID=c24a Rev=77.02
> S:  Manufacturer=Logitech
> S:  Product=Gaming Mouse G600
> ...
This means we need to listen to bus 3.  So 3u it is..
test it first
  cat /sys/kernel/debug/usb/usbmon/3u
works!
trying another variation
  sudo xfce4-terminal -x cat /sys/kernel/debug/usb/usbmon/3u
works!
Now doing the cat in a terminal that i can kill...
  sudo touch /tmp/usbmon.3u.mon
  sudo rm /tmp/usbmon.3u.mon
  sudo touch /tmp/usbmon.3u.mon
  sudo chown tulth.tulth /tmp/usbmon.3u.mon
  sudo echo 'cat /sys/kernel/debug/usb/usbmon/3u > /tmp/usbmon.3u.mon' > /tmp/do_usb_log.sh
  sudo chmod +x /tmp/do_usb_log.sh
  sudo -b xfce4-terminal -x  /tmp/do_usb_log.sh
finally!
move mouse and wait...
then...
  vusb-analyzer  /tmp/usbmon.3u.mon
works!
** DONE install second mouse to use while logging g600
   CLOSED: [2015-02-15 Sun 18:12]
** TODO log a mouse programming event
test with just using naga
  sudo -b xfce4-terminal -x  cat /sys/kernel/debug/usb/usbmon/3u
looks like it only sends messages on g600 events, not naga events
also, lsusb...
> Bus 002 Device 005: ID 1532:002e Razer USA, Ltd RZ01-0058 Gaming Mouse [Naga]
indicates the naga is on bus 2
strangely though, in windows10, whet the logitech gaming app is focused, a bunch of traffic happens

full test
  sudo touch /tmp/usbmon.3u.mon
  sudo rm /tmp/usbmon.3u.mon
  sudo touch /tmp/usbmon.3u.mon
  sudo chown tulth.tulth /tmp/usbmon.3u.mon
  sudo echo 'cat /sys/kernel/debug/usb/usbmon/3u > /tmp/usbmon.3u.mon' > /tmp/do_usb_log.sh
  sudo chmod +x /tmp/do_usb_log.sh
  sudo -b xfce4-terminal -x  /tmp/do_usb_log.sh
  sleep 1
  vusb-analyzer -t  /tmp/usbmon.3u.mon & 
then

** test: win10up, g600 directed to the win10, but NOT running logitech software...
start the loggering...
  sudo touch /tmp/usbmon.3u.mon
  sudo rm /tmp/usbmon.3u.mon
  sudo touch /tmp/usbmon.3u.mon
  sudo chown tulth.tulth /tmp/usbmon.3u.mon
  sudo echo 'cat /sys/kernel/debug/usb/usbmon/3u > /tmp/usbmon.3u.mon' > /tmp/do_usb_log.sh
  sudo chmod +x /tmp/do_usb_log.sh
  sudo -b xfce4-terminal -x  /tmp/do_usb_log.sh
  sleep 1
  xfce4-terminal -x  tail -f /tmp/usbmon.3u.mon
got the mouse upside down, i see the log empty
pressing gshift mouse key
saw some events pop up, these 4 lines:
> ffff88040716b540 1079376606 C Ii:3:002:2 0:1 6 = 80200000 0010
> ffff880037983b40 1079396474 S Ii:3:002:2 -115:1 32 <
> ffff880037983b40 1079605652 C Ii:3:002:2 0:1 6 = 80000000 0010
> ffff880037983f00 1079615975 S Ii:3:002:2 -115:1 32 <
okay, starting the logitech gaming software 8.57...
buncha spam!
copying this log for safekeeping...
  cp /tmp/usbmon.3u.mon ~/projects/logitech_g600/gshift_press_then_start_logitech_software.mon
now viewing it...
  vusb-analyzer  ~/projects/logitech_g600/gshift_press_then_start_logitech_software.mon
it seems to request a iserial, and flash version 3 times at start up
iserial request:
> ffff880395790f00 1152009228 S Ci:3:002:0 s 80 06 0303 0409 0102 258 <
> ffff880395790f00 1152010423 C Ci:3:002:0 0 34 = 22033300 31003700 43004100 45004600 35004500 34003700 43003000 30003100
> 0000: 22 03 33 00 31 00 37 00 43 00 41 00 45 00 46 00  ".3.1.7.C.A.E.F.
> 0010: 35 00 45 00 34 00 37 00 43 00 30 00 30 00 31 00  5.E.4.7.C.0.0.1.
why iserial? when I run 
  sudo lsusb -vv -d 046d:c24a
i see this line:
  iSerial                 3 317CAEF5E47C0017
Strangely, it is missing the last 7 in the usb request.
Flash version request:
> ffff880395790f00 1152013944 S Ci:3:002:0 s 80 06 0304 0409 0102 258 <
> ffff880395790f00 1152014604 C Ci:3:002:0 0 26 = 1a035500 37003700 2e003000 32005f00 42003000 30003100 3700
> 0000: 1A 03 55 00 37 00 37 00 2E 00 30 00 32 00 5F 00  ..U.7.7...0.2._.
> 0010: 42 00 30 00 30 00 31 00 37 00                    B.0.0.1.7.
why flash version?
if i go to the settintg in logitech gaming software 8.57...
then click g600 tab, it says firmware version U77.02_B0017

** test: win10up, g600 directed to the win10, AND AM running logitech software, on "home" tab
start the loggering...
  sudo touch /tmp/usbmon.3u.mon
  sudo rm /tmp/usbmon.3u.mon
  sudo touch /tmp/usbmon.3u.mon
  sudo chown tulth.tulth /tmp/usbmon.3u.mon
  sudo echo 'cat /sys/kernel/debug/usb/usbmon/3u > /tmp/usbmon.3u.mon' > /tmp/do_usb_log.sh
  sudo chmod +x /tmp/do_usb_log.sh
  sudo -b xfce4-terminal -x  /tmp/do_usb_log.sh
  sleep 1
  xfce4-terminal -x  tail -f /tmp/usbmon.3u.mon
clicking the "customize buttons tab"
then halting the log, and looking at it...
  cp /tmp/usbmon.3u.mon ~/projects/logitech_g600/switch_to_customize_buttons.mon
  vusb-analyzer ~/projects/logitech_g600/switch_to_customize_buttons.mon &
  find-file ~/projects/logitech_g600/switch_to_customize_buttons.mon
buncha spam with this interesting stuff in the middle:
> ffff8800c9603480 2534845418 S Ci:3:002:0 s a1 01 03f0 0001 0004 4 <
> ffff8800c9603480 2534846254 C Ci:3:002:0 0 4 = f0080000
the spam commands look like this:
> ffff880220d2d000 2534688278 S Ci:3:002:0 s a1 01 03f1 0001 0008 8 <
> ffff880220d2d000 2534689268 C Ci:3:002:0 0 8 = f100ff66 02040000

** test: win10up, g600 directed to the win10, AND AM running logitech software, on customize buttons tab
gshift key is set to gshift.
going to set it to back...
start the loggering...
  sudo touch /tmp/usbmon.3u.mon
  sudo rm /tmp/usbmon.3u.mon
  sudo touch /tmp/usbmon.3u.mon
  sudo chown tulth.tulth /tmp/usbmon.3u.mon
  sudo echo 'cat /sys/kernel/debug/usb/usbmon/3u > /tmp/usbmon.3u.mon' > /tmp/do_usb_log.sh
  sudo chmod +x /tmp/do_usb_log.sh
  sudo -b xfce4-terminal -x  /tmp/do_usb_log.sh
  sleep 1
  xfce4-terminal -x  tail -f /tmp/usbmon.3u.mon
clicking gshift and changing it from gshift to "back"...
then halting the log, and looking at it...
  cp /tmp/usbmon.3u.mon ~/projects/logitech_g600/gshift_to_back.mon
  vusb-analyzer ~/projects/logitech_g600/gshift_to_back.mon &
  find-file ~/projects/logitech_g600/gshift_to_back.mon
I tried the gshift in win10 chrome, and confirmed it does the back button function
buncha spam with this interesting stuff in the middle. this stuff seems to be the reprogram stuff..
"spam" message
> ffff8803bfd20840 2908027731 S Ci:3:002:0 s a1 01 03f1 0001 0008 8 <
> ffff8803bfd20840 2908028271 C Ci:3:002:0 0 8 = f10014ff 02040000
unknown command message
> ffff8803bfd20a80 2908040935 S Ci:3:002:0 s a1 01 03f0 0001 0004 4 <
> ffff8803bfd20a80 2908041141 C Ci:3:002:0 0 4 = f0080000
Now here things get interesting:
> ffff8803bfd20780 2908044595 S Co:3:002:0 s 21 09 03f3 0001 009a 154 = f3000000 02040000 00000000 00011800 00000000 00000000 02000000 00000001
> ffff8803bfd20780 2908050075 C Co:3:002:0 0 154 >
> ffff880007b03d80 2908058552 C Ii:3:002:2 0:1 6 = 80000000 0000
> ffff8803bfd20180 2908058812 S Ii:3:002:2 -115:1 32 <
unknown command message
> ffff8803bfd206c0 2908380498 S Ci:3:002:0 s a1 01 03f0 0001 0004 4 <
> ffff8803bfd206c0 2908386352 C Ci:3:002:0 0 4 = f0000000
unknown command message
> ffff8803bfd20b40 2908401688 S Ci:3:002:0 s a1 01 03f0 0001 0004 4 <
> ffff8803bfd20b40 2908407277 C Ci:3:002:0 0 4 = f0000000
unknown command message
> ffff8803bfd209c0 2908411426 S Ci:3:002:0 s a1 01 03f0 0001 0004 4 <
> ffff8803bfd209c0 2908418069 C Ci:3:002:0 0 4 = f0000000
"spam" message
> ffff8803bfd20600 2908450276 S Ci:3:002:0 s a1 01 03f1 0001 0008 8 <
> ffff8803bfd20600 2908456072 C Ci:3:002:0 0 8 = f10008ff 02040000
"spam" message
> ffff8803bfd20240 2908466678 S Ci:3:002:0 s a1 01 03f1 0001 0008 8 <
> ffff8803bfd20240 2908476330 C Ci:3:002:0 0 8 = f10008ff 02040000
"spam" message
> ffff8803bfd20240 2908518350 S Ci:3:002:0 s a1 01 03f1 0001 0008 8 <
> ffff8803bfd20240 2908527171 C Ci:3:002:0 0 8 = f10007ff 02040000
"spam" message
> ffff8803bfd20600 2908559599 S Ci:3:002:0 s a1 01 03f1 0001 0008 8 <
> ffff8803bfd20600 2908571386 C Ci:3:002:0 0 8 = f10006ff 02040000
send buttons clear, yes this message is identical to the gshift release press before!
> ffff8803bfd20180 2908572504 C Ii:3:002:2 0:1 6 = 80000000 0010
> ffff8803bfd209c0 2908573377 S Ii:3:002:2 -115:1 32 <
"spam" message
> ffff8803bfd20b40 2908584904 S Ci:3:002:0 s a1 01 03f1 0001 0008 8 <
> ffff8803bfd20b40 2908585338 C Ci:3:002:0 0 8 = f1ff0400 02040000

** test: win10up, g600 directed to the win10, AND AM running logitech software, on customize buttons tab...setting gshift from back to gshift
gshift key is set to "back".
going to set it to gshift...
start the loggering...
  sudo touch /tmp/usbmon.3u.mon
  sudo rm /tmp/usbmon.3u.mon
  sudo touch /tmp/usbmon.3u.mon
  sudo chown tulth.tulth /tmp/usbmon.3u.mon
  sudo echo 'cat /sys/kernel/debug/usb/usbmon/3u > /tmp/usbmon.3u.mon' > /tmp/do_usb_log.sh
  sudo chmod +x /tmp/do_usb_log.sh
  sudo -b xfce4-terminal -x  /tmp/do_usb_log.sh
  sleep 1
  xfce4-terminal -x  tail -f /tmp/usbmon.3u.mon
clicking gshift and changing it from "back" to "gshift"...
then halting the log, and looking at it...
  cp /tmp/usbmon.3u.mon ~/projects/logitech_g600/gshift_to_gshift.mon
  vusb-analyzer ~/projects/logitech_g600/gshift_to_gshift.mon &
  find-file ~/projects/logitech_g600/gshift_to_gshift.mon
I tried the gshift in win10 chrome, and confirmed it does the back button function
buncha spam with this interesting stuff in the middle. this stuff seems to be the reprogram stuff..
  ffff880037883180  134097793 S Co:3:002:0 s 21 09 03f3 0001 009a 154 = f3000000 02040000 00000000 00011800 00000000 00000000 02000000 00000001
> ffff8803bfd20780 2908044595 S Co:3:002:0 s 21 09 03f3 0001 009a 154 = f3000000 02040000 00000000 00011800 00000000 00000000 02000000 00000001
> ffff8803bfd20780 2908050075 C Co:3:002:0 0 154 >
> ffff880007b03d80 2908058552 C Ii:3:002:2 0:1 6 = 80000000 0000
> ffff8803bfd20180 2908058812 S Ii:3:002:2 -115:1 32 <

** trying wireshark
gshift to back
6e: 4
0000  c0 b9 98 7c 02 88 ff ff  53 02 00 02 03 00 00 00   ...|.... S.......
0010  e0 55 e1 54 00 00 00 00  c0 77 04 00 8d ff ff ff   .U.T.... .w......
0020  9a 00 00 00 9a 00 00 00  21 09 f3 03 01 00 9a 00   ........ !.......
0030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
data:
0040  f3 00 00 00 02 04 00 00  00 00 00 00 00 01 18 00   ........ ........
0050  00 00 00 00 00 00 00 00  02 00 00 00 00 00 00 01   ........ ........
0060  00 00 02 00 00 03 00 00  04 00 00 05 00 00 04 00   ........ ........
0070  00 00 02 05 14 00 00 00  00 1e 00 00 1f 00 00 20   ........ ....... 
0080  00 00 21 00 00 22 00 00  23 00 00 24 00 00 25 00   ..!..".. #..$..%.
0090  00 26 00 00 27 00 00 2d  00 00 2e 00 00 00 01 00   .&..'..- ........
00a0  00 02 00 00 03 00 00 04  00 00 05 00 00 17 00 00   ........ ........
00b0  00 02 05 14 00 00 00 01  1e 00 01 1f 00 01 20 00   ........ ...... .
00c0  01 21 00 01 22 00 01 23  00 01 24 00 01 25 00 01   .!.."..# ..$..%..
00d0  26 00 01 27 00 01 2d 00  01 2e                     &..'..-. ..      

back to gshift
6e: 17
0000  00 5c d1 eb 03 88 ff ff  53 02 00 02 03 00 00 00   .\...... S.......
0010  f1 55 e1 54 00 00 00 00  61 39 07 00 8d ff ff ff   .U.T.... a9......
0020  9a 00 00 00 9a 00 00 00  21 09 f3 03 01 00 9a 00   ........ !.......
0030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
data:
0040  f3 00 00 00 02 04 00 00  00 00 00 00 00 01 18 00   ........ ........
0050  00 00 00 00 00 00 00 00  02 00 00 00 00 00 00 01   ........ ........
0060  00 00 02 00 00 03 00 00  04 00 00 05 00 00 17 00   ........ ........
0070  00 00 02 05 14 00 00 00  00 1e 00 00 1f 00 00 20   ........ ....... 
0080  00 00 21 00 00 22 00 00  23 00 00 24 00 00 25 00   ..!..".. #..$..%.
0090  00 26 00 00 27 00 00 2d  00 00 2e 00 00 00 01 00   .&..'..- ........
00a0  00 02 00 00 03 00 00 04  00 00 05 00 00 17 00 00   ........ ........
00b0  00 02 05 14 00 00 00 01  1e 00 01 1f 00 01 20 00   ........ ...... .
00c0  01 21 00 01 22 00 01 23  00 01 24 00 01 25 00 01   .!.."..# ..$..%..
00d0  26 00 01 27 00 01 2d 00  01 2e                     &..'..-. ..      

to leftclick
6e: 01
0000  80 b4 16 07 04 88 ff ff  53 02 00 02 03 00 00 00   ........ S.......
0010  cb 5b e1 54 00 00 00 00  a7 50 06 00 8d ff ff ff   .[.T.... .P......
0020  9a 00 00 00 9a 00 00 00  21 09 f3 03 01 00 9a 00   ........ !.......
0030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
0040  f3 00 00 00 02 04 00 00  00 00 00 00 00 01 18 00   ........ ........
0050  00 00 00 00 00 00 00 00  02 00 00 00 00 00 00 01   ........ ........
0060  00 00 02 00 00 03 00 00  04 00 00 05 00 00 01 00   ........ ........
0070  00 00 02 05 14 00 00 00  00 1e 00 00 1f 00 00 20   ........ ....... 
0080  00 00 21 00 00 22 00 00  23 00 00 24 00 00 25 00   ..!..".. #..$..%.
0090  00 26 00 00 27 00 00 2d  00 00 2e 00 00 00 01 00   .&..'..- ........
00a0  00 02 00 00 03 00 00 04  00 00 05 00 00 17 00 00   ........ ........
00b0  00 02 05 14 00 00 00 01  1e 00 01 1f 00 01 20 00   ........ ...... .
00c0  01 21 00 01 22 00 01 23  00 01 24 00 01 25 00 01   .!.."..# ..$..%..
00d0  26 00 01 27 00 01 2d 00  01 2e                     &..'..-. ..      

middle click to gshift
65: 03=>17
a4: 03=>17
0000  c0 66 c9 eb 03 88 ff ff  53 02 00 02 03 00 00 00   .f...... S.......
0010  df 5c e1 54 00 00 00 00  48 5a 0e 00 8d ff ff ff   .\.T.... HZ......
0020  9a 00 00 00 9a 00 00 00  21 09 f3 03 01 00 9a 00   ........ !.......
0030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
0040  f3 00 00 00 02 04 00 00  00 00 00 00 00 01 18 00   ........ ........
0050  00 00 00 00 00 00 00 00  02 00 00 00 00 00 00 01   ........ ........
0060  00 00 02 00 00 17 00 00  04 00 00 05 00 00 17 00   ........ ........
0070  00 00 02 05 14 00 00 00  00 1e 00 00 1f 00 00 20   ........ ....... 
0080  00 00 21 00 00 22 00 00  23 00 00 24 00 00 25 00   ..!..".. #..$..%.
0090  00 26 00 00 27 00 00 2d  00 00 2e 00 00 00 01 00   .&..'..- ........
00a0  00 02 00 00 17 00 00 04  00 00 05 00 00 17 00 00   ........ ........
00b0  00 02 05 14 00 00 00 01  1e 00 01 1f 00 01 20 00   ........ ...... .
00c0  01 21 00 01 22 00 01 23  00 01 24 00 01 25 00 01   .!.."..# ..$..%..
00d0  26 00 01 27 00 01 2d 00  01 2e                     &..'..-. ..      

okay, this time i set "button side" to the key, T
0000  40 32 1c db 03 88 ff ff  53 02 00 03 03 00 00 00   @2...... S.......
0010  c7 a6 e2 54 00 00 00 00  fb 0b 0e 00 8d ff ff ff   ...T.... ........
0020  9a 00 00 00 9a 00 00 00  21 09 f3 03 01 00 9a 00   ........ !.......
0030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
0040  f3 00 00 00 02 04 00 00  00 00 00 00 00 01 18 00   ........ ........
0050  00 00 00 00 00 00 00 00  02 00 00 00 00 00 00 01   ........ ........
0060  00 00 02 00 00 03 00 00  04 00 00 05 00 00 00 00   ........ ........
0070  17 00 00 00 00 00 00 02  05 14 00 00 00 00 1e 00   ........ ........
0080  5b 00 00 5c 00 00 5d 00  00 5e 00 00 5f 00 00 00   [..\..]. .^.._...
0090  05 00 00 12 00 00 00 00  08 04 00 00 ff ff ff 00   ........ ........
00a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00b0  00 00 00 00 14 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00d0  00 00 00 00 00 00 00 00  00 00                     ........ ..      
wow thats really different
set "button side" to the key, S
0000  80 b1 66 50 00 88 ff ff  53 02 00 03 03 00 00 00   ..fP.... S.......
0010  b9 a7 e2 54 00 00 00 00  90 01 01 00 8d ff ff ff   ...T.... ........
0020  9a 00 00 00 9a 00 00 00  21 09 f3 03 01 00 9a 00   ........ !.......
0030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
0040  f3 00 00 00 02 04 00 00  00 00 00 00 00 01 18 00   ........ ........
0050  00 00 00 00 00 00 00 00  02 00 00 00 00 00 00 01   ........ ........
0060  00 00 02 00 00 03 00 00  04 00 00 05 00 00 00 00   ........ ........
0070  16 00 00 00 00 00 00 02  05 14 00 00 00 00 1e 00   ........ ........
0080  5b 00 00 5c 00 00 5d 00  00 5e 00 00 5f 00 00 00   [..\..]. .^.._...
0090  05 00 00 12 00 00 00 00  08 04 00 00 ff ff ff 00   ........ ........
00a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00b0  00 00 00 00 14 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00d0  00 00 00 00 00 00 00 00  00 00                     ........ ..      
diff is byte 70, was 17, then became 16
Aha! keyboard scan codes
Keycode Symbol      Short name      Description
--------------------------------------------------------------------------------
KC_S                                16 Keyboard s and S
KC_T                                17 Keyboard t and T
from here:  /home/tulth/projects/ergodox/tmk_keyboard/doc/keycode.txt
but what in the world is all the other junk?
I went and set it back to mouse left click, and it sent this
0000  00 49 d8 06 04 88 ff ff  53 02 00 03 03 00 00 00   .I...... S.......
0010  ed a9 e2 54 00 00 00 00  d8 bd 0d 00 8d ff ff ff   ...T.... ........
0020  9a 00 00 00 9a 00 00 00  21 09 f3 03 01 00 9a 00   ........ !.......
0030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
0040  f3 00 00 00 02 04 00 00  00 00 00 00 00 01 18 00   ........ ........
0050  00 00 00 00 00 00 00 00  02 00 00 00 00 00 00 01   ........ ........
0060  00 00 02 00 00 03 00 00  04 00 00 05 00 00 01 00   ........ ........
0070  00 00 00 00 00 00 00 02  05 14 00 00 00 00 1e 00   ........ ........
0080  5b 00 00 5c 00 00 5d 00  00 5e 00 00 5f 00 00 00   [..\..]. .^.._...
0090  05 00 00 12 00 00 00 00  08 04 00 00 ff ff ff 00   ........ ........
00a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00b0  00 00 00 00 14 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00d0  00 00 00 00 00 00 00 00  00 00                     ........ ..      

It really seems like the stuff after 0x80 is trash...
theory:
40-5e: ???
5F: "Button Left"
60: "Button Left"
61: "Button Left"
62: "Button Right"
63: "Button Right"
64: "Button Right"
65: "Button Middle"
66: "Button Middle"
67: "Button Middle"
68: "Button Horiz Wheel Left" 
69: "Button Horiz Wheel Left"
6a: "Button Horiz Wheel Left"
6b: "Button Horiz Wheel Right" 
6c: "Button Horiz Wheel Right"
6d: "Button Horiz Wheel Right"
6e: "button side" mouse button, mouse button definition, (0 means keypress?)
6f: "button side" mouse button, ?keyboard modifiers
70: "button side" mouse button, key definition

setting "button side" to left ctrl + T
0000  c0 dc e7 93 02 88 ff ff  53 02 00 03 03 00 00 00   ........ S.......
0010  60 ae e2 54 00 00 00 00  ed 56 0e 00 8d ff ff ff   `..T.... .V......
0020  9a 00 00 00 9a 00 00 00  21 09 f3 03 01 00 9a 00   ........ !.......
0030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
0040  f3 00 00 00 02 04 00 00  00 00 00 00 00 01 18 00   ........ ........
0050  00 00 00 00 00 00 00 00  02 00 00 00 00 00 00 01   ........ ........
0060  00 00 02 00 00 03 00 00  04 00 00 05 00 00 00 01   ........ ........
0070  17 00 02 05 14 00 00 00  00 1e 00 00 1f 00 00 20   ........ ....... 
0080  00 00 21 00 00 22 00 00  23 00 00 24 00 00 25 00   ..!..".. #..$..%.
0090  00 26 00 00 27 00 00 2d  00 00 2e 00 ff ff ff 00   .&..'..- ........
00a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00b0  00 00 00 14 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00d0  00 00 00 00 00 00 00 00  00 00                     ........ ..      

I suppose 5F being 01 means left control
I think this table below has the bitwise "modifiers:

KC_LCTRL            KC_LCTRL        E0 Keyboard LeftControl
KC_LSHIFT           KC_LSFT         E1 Keyboard LeftShift
KC_LALT                             E2 Keyboard LeftAlt
KC_LGUI                             E3 Keyboard Left GUI(Windows/Apple/Meta key)
KC_RCTRL            KC_RCTL         E4 Keyboard RightControl
KC_RSHIFT           KC_RSFT         E5 Keyboard RightShift
KC_RALT                             E6 Keyboard RightAlt
KC_RGUI                             E7 Keyboard Right GUI(Windows/Apple/Meta key)

So, when does it look like when the logitech gaming software polls for the current settings?
3 transactions
*** t0
request: (look@2A!)
0000  00 06 79 95 03 88 ff ff  53 02 80 03 03 00 00 3c   ..y..... S......<
0010  e8 b3 e2 54 00 00 00 00  75 0e 0f 00 8d ff ff ff   ...T.... u.......
0020  9a 00 00 00 00 00 00 00  a1 01 f3 03 01 00 9a 00   ........ ........
0030  00 00 00 00 00 00 00 00  00 02 00 00 00 00 00 00   ........ ........
response:
0000  00 06 79 95 03 88 ff ff  43 02 80 03 03 00 2d 00   ..y..... C.....-.
0010  e8 b3 e2 54 00 00 00 00  66 21 0f 00 00 00 00 00   ...T.... f!......
0020  9a 00 00 00 9a 00 00 00  00 00 00 00 00 00 00 00   ........ ........
0030  00 00 00 00 00 00 00 00  00 02 00 00 00 00 00 00   ........ ........
0040  f3 00 00 00 02 04 00 00  00 00 00 00 00 01 18 00   ........ ........
0050  00 00 00 00 00 00 00 00  02 00 00 00 00 00 00 01   ........ ........
0060  00 00 02 00 00 03 00 00  04 00 00 05 00 00 00 80   ........ ........
0070  17 17 00 02 17 00 00 00  00 00 1e 00 00 1f 00 00   ........ ........
0080  5b 00 00 5c 00 00 5d 00  00 5e 00 00 5f 00 00 00   [..\..]. .^.._...
0090  05 00 00 12 00 00 00 00  08 04 00 00 ff ff ff 00   ........ ........
00a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00b0  00 00 00 17 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00d0  00 00 00 00 00 00 00 00  00 00                     ........ ..      
*** t1
request: (look@2A!)
0000  00 0f 79 95 03 88 ff ff  53 02 80 03 03 00 00 3c   ..y..... S......<
0010  e9 b3 e2 54 00 00 00 00  d3 00 00 00 8d ff ff ff   ...T.... ........
0020  9a 00 00 00 00 00 00 00  a1 01 f4 03 01 00 9a 00   ........ ........
0030  00 00 00 00 00 00 00 00  00 02 00 00 00 00 00 00   ........ ........
response:
0000  00 0f 79 95 03 88 ff ff  43 02 80 03 03 00 2d 00   ..y..... C.....-.
0010  e9 b3 e2 54 00 00 00 00  fa 11 00 00 00 00 00 00   ...T.... ........
0020  9a 00 00 00 9a 00 00 00  00 00 00 00 00 00 00 00   ........ ........
0030  00 00 00 00 00 00 00 00  00 02 00 00 00 00 00 00   ........ ........
0040  f4 ff ff ff 00 00 00 00  00 00 00 00 00 01 18 00   ........ ........
0050  00 00 00 00 00 00 00 00  02 00 00 00 00 00 00 01   ........ ........
0060  00 00 02 00 00 03 00 00  04 00 00 05 00 00 17 00   ........ ........
0070  00 00 02 05 17 00 00 00  00 59 00 00 5a 00 00 5b   ........ .Y..Z..[
0080  00 00 5c 00 00 5d 00 00  5e 00 00 5f 00 00 60 00   ..\..].. ^.._..`.
0090  00 61 00 00 62 00 00 56  00 00 57 ff ff ff 01 00   .a..b..V ..W.....
00a0  00 02 00 00 03 00 00 04  00 00 05 00 00 17 00 00   ........ ........
00b0  00 02 05 17 00 00 00 01  59 00 01 5a 00 01 5b 00   ........ Y..Z..[.
00c0  01 5c 00 01 5d 00 01 5e  00 01 5f 00 01 60 00 01   .\..]..^ .._..`..
00d0  61 00 01 62 00 01 56 00  01 57                     a..b..V. .W      
*** t2
request: (look@2A!)
0000  00 63 3b 1a 01 88 ff ff  53 02 80 03 03 00 00 3c   .c;..... S......<
0010  e9 b3 e2 54 00 00 00 00  b6 39 00 00 8d ff ff ff   ...T.... .9......
0020  9a 00 00 00 00 00 00 00  a1 01 f5 03 01 00 9a 00   ........ ........
0030  00 00 00 00 00 00 00 00  00 02 00 00 00 00 00 00   ........ ........
Notes:
bmRequestType = 0xA1 (device2host, class 0x01, recipient interface 0x01)
bRequest = 0x01
wValue = 0x03f5 (report id=245 (0xf5), feature=3)
wIndex = 1
wLength = 154 (0x009A), note that 64+154 is 218, the response packet length

response:
0000  00 63 3b 1a 01 88 ff ff  43 02 80 03 03 00 2d 00   .c;..... C.....-.
0010  e9 b3 e2 54 00 00 00 00  8c 4c 00 00 00 00 00 00   ...T.... .L......
0020  9a 00 00 00 9a 00 00 00  00 00 00 00 00 00 00 00   ........ ........
0030  00 00 00 00 00 00 00 00  00 02 00 00 00 00 00 00   ........ ........
0040  f5 00 ff 00 01 04 00 00  00 00 00 00 1a 01 1a 00   ........ ........
0050  00 00 00 00 00 00 00 00  02 00 00 00 00 00 00 01   ........ ........
0060  00 00 02 00 00 03 00 00  04 00 00 05 00 00 15 00   ........ ........
0070  00 13 00 00 17 00 00 00  00 1e 00 00 1f 00 00 20   ........ ....... 
0080  00 00 21 00 00 22 00 00  23 11 00 00 16 00 00 05   ..!..".. #.......
0090  00 00 12 00 00 00 00 08  04 00 00 ff ff ff 00 00   ........ ........
00a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00b0  00 00 00 17 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00d0  00 00 00 00 00 00 00 00  00 00                     ........ ..      



okay, time for an adventure in programming on the next page

* Endpoint notes
EP1: mouse movement, mouse buttons?
EP2: button presses
EP3: ??
EP4: ??


* xinput fun
  xinput list-props 8 
1 > 	Button Labels (288):	"Button Left" (154),
 "Button Middle" (155),
 "Button Right" (156),
 "Button Wheel Up" (157),
 "Button Wheel Down" (158),
8 "Button Horiz Wheel Left" (159),
9 "Button Horiz Wheel Right" (160),xinput list-props 8 
10 "Button Side" (273),
 "Button Extra" (274),
 "Button Forward" (275),
 "Button Back" (276),
 "Button Task" (277), "Button Unknown" (272), "Button Unknown" (272), "Button Unknown" (272), "Button Unknown" (272), "Button Unknown" (272), "Button Unknown" (272), "Button Unknown" (272), "Button Unknown" (272), "Button Unknown" (272), "Button Unknown" (272), "Button Unknown" (272), "Button Unknown" (272)

* xev fun
** 1 "Button Left" (154)
ButtonPress event, serial 37, synthetic NO, window 0x5400001,
    root 0x29b, subw 0x0, time 47207306, (367,221), root:(2163,951),
    state 0x0, button 1, same_screen YES

** 3 "Button Right" (156),
ButtonPress event, serial 37, synthetic NO, window 0x5400001,
    root 0x29b, subw 0x0, time 47264567, (193,135), root:(1989,865),
    state 0x0, button 3, same_screen YES

* did a f3 read packet
"rainbow mode"
| 0x40 | 0xf3 |                                |
| 0x41 |  0x0 | led red                        |
| 0x42 |  0x0 | led green                      |
| 0x43 |  0x0 | led blue                       |
| 0x44 |  0x2 | ?lighting 0=no,1=pulse,2=cycle |
| 0x45 |  0x4 |                                |
| 0x46 |  0x0 |                                |
| 0x47 |  0x0 |                                |
| 0x48 |  0x0 |                                |
| 0x49 |  0x0 |                                |
| 0x4a |  0x0 |                                |
| 0x4b |  0x0 | poll rate (1000/(PR+1))        |
| 0x4c |  0x0 | shift DPI                      |
| 0x4d |  0x1 | default dpi index              |
| 0x4e | 0x18 | DPI1/50                        |
| 0x4f |  0x0 | DPI2/50                        |
| 0x50 |  0x0 | DPI3/50                        |
| 0x51 |  0x0 | DPI4/50                        |
| 0x52 |  0x0 |                                |
| 0x53 |  0x0 |                                |
| 0x54 |  0x0 |                                |
| 0x55 |  0x0 |                                |
| 0x56 |  0x0 |                                |
| 0x57 |  0x0 |                                |
| 0x58 |  0x2 |                                |
| 0x59 |  0x0 |                                |
| 0x5a |  0x0 |                                |
| 0x5b |  0x0 |                                |
| 0x5c |  0x0 |                                |
| 0x5d |  0x0 |                                |
| 0x5e |  0x0 |                                |
| 0x5f |  0x1 | button left                    |
| 0x60 |  0x0 | button left                    |
| 0x61 |  0x0 | button left                    |
| 0x62 |  0x2 | button right                   |
| 0x63 |  0x0 | button right                   |
| 0x64 |  0x0 | button right                   |
| 0x65 |  0x3 | button middle                  |
| 0x66 |  0x0 | button middle                  |
| 0x67 |  0x0 | button middle                  |
| 0x68 |  0x4 | button horiz wheel left        |
| 0x69 |  0x0 | button horiz wheel left        |
| 0x6a |  0x0 | button horiz wheel left        |
| 0x6b |  0x5 | button horiz wheel right       |
| 0x6c |  0x0 | button horiz wheel right       |
| 0x6d |  0x0 | button horiz wheel right       |
| 0x6e | 0x17 | button side                    |
| 0x6f |  0x0 | button side                    |
| 0x70 |  0x0 | button side                    |
| 0x71 |  0x0 | button back (g7)               |
| 0x72 |  0x2 | button back (g7)               |
| 0x73 |  0x5 | button back (g7)               |
| 0x74 | 0x14 | button forward (g8)            |
| 0x75 |  0x0 | button forward (g8)            |
| 0x76 |  0x0 | button forward (g8)            |
| 0x77 |  0x0 | g9                             |
| 0x78 |  0x0 | g9                             |
| 0x79 | 0x1e | g9                             |
| 0x7a |  0x0 | g10                            |
| 0x7b |  0x0 | g10                            |
| 0x7c | 0x1f | g10                            |
| 0x7d |  0x0 | g11                            |
| 0x7e |  0x0 | g11                            |
| 0x7f | 0x20 | g11                            |
| 0x80 |  0x0 | g12                            |
| 0x81 |  0x0 | g12                            |
| 0x82 | 0x21 | g12                            |
| 0x83 |  0x0 | g13                            |
| 0x84 |  0x0 | g13                            |
| 0x85 | 0x22 | g13                            |
| 0x86 |  0x0 | g14                            |
| 0x87 |  0x0 | g14                            |
| 0x88 | 0x23 | g14                            |
| 0x89 |  0x0 | g15                            |
| 0x8a |  0x0 | g15                            |
| 0x8b | 0x24 | g15                            |
| 0x8c |  0x0 | g16                            |
| 0x8d |  0x0 | g16                            |
| 0x8e | 0x25 | g16                            |
| 0x8f |  0x0 | g17                            |
| 0x90 |  0x0 | g17                            |
| 0x91 | 0x26 | g17                            |
| 0x92 |  0x0 | g18                            |
| 0x93 |  0x0 | g18                            |
| 0x94 | 0x27 | g18                            |
| 0x95 |  0x0 | g19                            |
| 0x96 |  0x0 | g19                            |
| 0x97 | 0x2d | g19                            |
| 0x98 |  0x0 | g20                            |
| 0x99 |  0x0 | g20                            |
| 0x9a | 0x2e | g20                            |
| 0x9b |  0x0 | padding                        |
| 0x9c | 0xff | padding                        |
| 0x9d | 0xff | padding                        |
| 0x9e | 0xff | button left                    |
| 0x9f |  0x0 | button left                    |
| 0xa0 |  0x0 | button left                    |
| 0xa1 |  0x0 | button right                   |
| 0xa2 |  0x0 | button right                   |
| 0xa3 |  0x0 | button right                   |
| 0xa4 |  0x0 | button middle                  |
| 0xa5 |  0x0 | button middle                  |
| 0xa6 |  0x0 | button middle                  |
| 0xa7 |  0x0 | button horiz wheel left        |
| 0xa8 |  0x0 | button horiz wheel left        |
| 0xa9 |  0x0 | button horiz wheel left        |
| 0xaa |  0x0 | button horiz wheel right       |
| 0xab |  0x0 | button horiz wheel right       |
| 0xac |  0x0 | button horiz wheel right       |
| 0xad |  0x0 | button side                    |
| 0xae |  0x0 | button side                    |
| 0xaf |  0x0 | button side                    |
| 0xb0 |  0x0 | button back (g7)               |
| 0xb1 |  0x0 | button back (g7)               |
| 0xb2 |  0x0 | button back (g7)               |
| 0xb3 | 0x14 | button forward (g8)            |
| 0xb4 |  0x0 | button forward (g8)            |
| 0xb5 |  0x0 | button forward (g8)            |
| 0xb6 |  0x0 | g9                             |
| 0xb7 |  0x0 | g9                             |
| 0xb8 |  0x0 | g9                             |
| 0xb9 |  0x0 | g10                            |
| 0xba |  0x0 | g10                            |
| 0xbb |  0x0 | g10                            |
| 0xbc |  0x0 | g11                            |
| 0xbd |  0x0 | g11                            |
| 0xbe |  0x0 | g11                            |
| 0xbf |  0x0 | g12                            |
| 0xc0 |  0x0 | g12                            |
| 0xc1 |  0x0 | g12                            |
| 0xc2 |  0x0 | g13                            |
| 0xc3 |  0x0 | g13                            |
| 0xc4 |  0x0 | g13                            |
| 0xc5 |  0x0 | g14                            |
| 0xc6 |  0x0 | g14                            |
| 0xc7 |  0x0 | g14                            |
| 0xc8 |  0x0 | g15                            |
| 0xc9 |  0x0 | g15                            |
| 0xca |  0x0 | g15                            |
| 0xcb |  0x0 | g16                            |
| 0xcc |  0x0 | g16                            |
| 0xcd |  0x0 | g16                            |
| 0xce |  0x0 | g17                            |
| 0xcf |  0x0 | g17                            |
| 0xd0 |  0x0 | g17                            |
| 0xd1 |  0x0 | g18                            |
| 0xd2 |  0x0 | g18                            |
| 0xd3 |  0x0 | g18                            |
| 0xd4 |  0x0 | g19                            |
| 0xd5 |  0x0 | g19                            |
| 0xd6 |  0x0 | g19                            |
| 0xd7 |  0x0 | g20                            |
| 0xd8 |  0x0 | g20                            |
| 0xd9 |  0x0 | g20                            |

* f4
"white mode"
| 0x40 | 0xf4 |                          |
| 0x41 | 0xff | led red                  |
| 0x42 | 0xff | led green                |
| 0x43 | 0xff | led blue                 |
| 0x44 |  0x0 |                          |
| 0x45 |  0x0 |                          |
| 0x46 |  0x0 |                          |
| 0x47 |  0x0 |                          |
| 0x48 |  0x0 |                          |
| 0x49 |  0x0 |                          |
| 0x4a |  0x0 |                          |
| 0x4b |  0x0 |                          |
| 0x4c |  0x0 |                          |
| 0x4d |  0x1 |                          |
| 0x4e | 0x18 | DPI/50                   |
| 0x4f |  0x0 | ?DPI                     |
| 0x50 |  0x0 | ?DPI                     |
| 0x51 |  0x0 | ?DPI                     |
| 0x52 |  0x0 |                          |
| 0x53 |  0x0 |                          |
| 0x54 |  0x0 |                          |
| 0x55 |  0x0 |                          |
| 0x56 |  0x0 |                          |
| 0x57 |  0x0 |                          |
| 0x58 |  0x2 |                          |
| 0x59 |  0x0 |                          |
| 0x5a |  0x0 |                          |
| 0x5b |  0x0 |                          |
| 0x5c |  0x0 |                          |
| 0x5d |  0x0 |                          |
| 0x5e |  0x0 |                          |
| 0x5f |  0x1 | button left              |
| 0x60 |  0x0 | button left              |
| 0x61 |  0x0 | button left              |
| 0x62 |  0x2 | button right             |
| 0x63 |  0x0 | button right             |
| 0x64 |  0x0 | button right             |
| 0x65 |  0x3 | button middle            |
| 0x66 |  0x0 | button middle            |
| 0x67 |  0x0 | button middle            |
| 0x68 |  0x4 | button horiz wheel left  |
| 0x69 |  0x0 | button horiz wheel left  |
| 0x6a |  0x0 | button horiz wheel left  |
| 0x6b |  0x5 | button horiz wheel right |
| 0x6c |  0x0 | button horiz wheel right |
| 0x6d |  0x0 | button horiz wheel right |
| 0x6e | 0x17 | button side              |
| 0x6f |  0x0 | button side              |
| 0x70 |  0x0 | button side              |
| 0x71 |  0x0 | button back (g7)         |
| 0x72 |  0x2 | button back (g7)         |
| 0x73 |  0x5 | button back (g7)         |
| 0x74 | 0x14 | button forward (g8)      |
| 0x75 |  0x0 | button forward (g8)      |
| 0x76 |  0x0 | button forward (g8)      |
| 0x77 |  0x0 | g9                       |
| 0x78 |  0x0 | g9                       |
| 0x79 | 0x59 | g9                       |
| 0x7a |  0x0 | g10                      |
| 0x7b |  0x0 | g10                      |
| 0x7c | 0x5a | g10                      |
| 0x7d |  0x0 | g11                      |
| 0x7e |  0x0 | g11                      |
| 0x7f | 0x5b | g11                      |
| 0x80 |  0x0 | g12                      |
| 0x81 |  0x0 | g12                      |
| 0x82 | 0x5c | g12                      |
| 0x83 |  0x0 | g13                      |
| 0x84 |  0x0 | g13                      |
| 0x85 | 0x5d | g13                      |
| 0x86 |  0x0 | g14                      |
| 0x87 |  0x0 | g14                      |
| 0x88 | 0x5e | g14                      |
| 0x89 |  0x0 | g15                      |
| 0x8a |  0x0 | g15                      |
| 0x8b | 0x5f | g15                      |
| 0x8c |  0x0 | g16                      |
| 0x8d |  0x0 | g16                      |
| 0x8e | 0x60 | g16                      |
| 0x8f |  0x0 | g17                      |
| 0x90 |  0x0 | g17                      |
| 0x91 | 0x61 | g17                      |
| 0x92 |  0x0 | g18                      |
| 0x93 |  0x0 | g18                      |
| 0x94 | 0x62 | g18                      |
| 0x95 |  0x0 | g19                      |
| 0x96 |  0x0 | g19                      |
| 0x97 | 0x56 | g19                      |
| 0x98 |  0x0 | g20                      |
| 0x99 |  0x0 | g20                      |
| 0x9a | 0x57 | g20                      |
| 0x9b | 0xff | ?stuffing                |
| 0x9c | 0xff | ?stuffing                |
| 0x9d | 0xff | ?stuffing                |
| 0x9e |  0x1 | button left              |
| 0x9f |  0x0 | button left              |
| 0xa0 |  0x0 | button left              |
| 0xa1 |  0x2 | button right             |
| 0xa2 |  0x0 | button right             |
| 0xa3 |  0x0 | button right             |
| 0xa4 |  0x3 | button middle            |
| 0xa5 |  0x0 | button middle            |
| 0xa6 |  0x0 | button middle            |
| 0xa7 |  0x4 | button horiz wheel left  |
| 0xa8 |  0x0 | button horiz wheel left  |
| 0xa9 |  0x0 | button horiz wheel left  |
| 0xaa |  0x5 | button horiz wheel right |
| 0xab |  0x0 | button horiz wheel right |
| 0xac |  0x0 | button horiz wheel right |
| 0xad | 0x17 | button side              |
| 0xae |  0x0 | button side              |
| 0xaf |  0x0 | button side              |
| 0xb0 |  0x0 | button back (g7)         |
| 0xb1 |  0x2 | button back (g7)         |
| 0xb2 |  0x5 | button back (g7)         |
| 0xb3 | 0x14 | button forward (g8)      |
| 0xb4 |  0x0 | button forward (g8)      |
| 0xb5 |  0x0 | button forward (g8)      |
| 0xb6 |  0x0 | g9                       |
| 0xb7 |  0x1 | g9                       |
| 0xb8 | 0x59 | g9                       |
| 0xb9 |  0x0 | g10                      |
| 0xba |  0x1 | g10                      |
| 0xbb | 0x5a | g10                      |
| 0xbc |  0x0 | g11                      |
| 0xbd |  0x1 | g11                      |
| 0xbe | 0x5b | g11                      |
| 0xbf |  0x0 | g12                      |
| 0xc0 |  0x1 | g12                      |
| 0xc1 | 0x5c | g12                      |
| 0xc2 |  0x0 | g13                      |
| 0xc3 |  0x1 | g13                      |
| 0xc4 | 0x5d | g13                      |
| 0xc5 |  0x0 | g14                      |
| 0xc6 |  0x1 | g14                      |
| 0xc7 | 0x5e | g14                      |
| 0xc8 |  0x0 | g15                      |
| 0xc9 |  0x1 | g15                      |
| 0xca | 0x5f | g15                      |
| 0xcb |  0x0 | g16                      |
| 0xcc |  0x1 | g16                      |
| 0xcd | 0x60 | g16                      |
| 0xce |  0x0 | g17                      |
| 0xcf |  0x1 | g17                      |
| 0xd0 | 0x61 | g17                      |
| 0xd1 |  0x0 | g18                      |
| 0xd2 |  0x1 | g18                      |
| 0xd3 | 0x62 | g18                      |
| 0xd4 |  0x0 | g19                      |
| 0xd5 |  0x1 | g19                      |
| 0xd6 | 0x56 | g19                      |
| 0xd7 |  0x0 | g20                      |
| 0xd8 |  0x1 | g20                      |
| 0xd9 | 0x57 | g20                      |

* f5
"green mode"
| 0x40 | 0xf5 |                          |
| 0x41 |  0x0 | led red                  |
| 0x42 | 0xff | led green                |
| 0x43 |  0x0 | led blue                 |
| 0x44 |  0x1 |                          |
| 0x45 |  0x4 |                          |
| 0x46 |  0x0 |                          |
| 0x47 |  0x0 |                          |
| 0x48 |  0x0 |                          |
| 0x49 |  0x0 |                          |
| 0x4a |  0x0 |                          |
| 0x4b |  0x0 |                          |
| 0x4c | 0x1a |                          |
| 0x4d |  0x1 |                          |
| 0x4e | 0x1a | DPI/50                   |
| 0x4f |  0x0 | ?DPI                     |
| 0x50 |  0x0 | ?DPI                     |
| 0x51 |  0x0 | ?DPI                     |
| 0x52 |  0x0 |                          |
| 0x53 |  0x0 |                          |
| 0x54 |  0x0 |                          |
| 0x55 |  0x0 |                          |
| 0x56 |  0x0 |                          |
| 0x57 |  0x0 |                          |
| 0x58 |  0x2 |                          |
| 0x59 |  0x0 |                          |
| 0x5a |  0x0 |                          |
| 0x5b |  0x0 |                          |
| 0x5c |  0x0 |                          |
| 0x5d |  0x0 |                          |
| 0x5e |  0x0 |                          |
| 0x5f |  0x1 | button left              |
| 0x60 |  0x0 | button left              |
| 0x61 |  0x0 | button left              |
| 0x62 |  0x2 | button right             |
| 0x63 |  0x0 | button right             |
| 0x64 |  0x0 | button right             |
| 0x65 |  0x3 | button middle            |
| 0x66 |  0x0 | button middle            |
| 0x67 |  0x0 | button middle            |
| 0x68 |  0x4 | button horiz wheel left  |
| 0x69 |  0x0 | button horiz wheel left  |
| 0x6a |  0x0 | button horiz wheel left  |
| 0x6b |  0x5 | button horiz wheel right |
| 0x6c |  0x0 | button horiz wheel right |
| 0x6d |  0x0 | button horiz wheel right |
| 0x6e | 0x15 | button side              |
| 0x6f |  0x0 | button side              |
| 0x70 |  0x0 | button side              |
| 0x71 | 0x13 | button back (g7)         |
| 0x72 |  0x0 | button back (g7)         |
| 0x73 |  0x0 | button back (g7)         |
| 0x74 | 0x14 | button forward (g8)      |
| 0x75 |  0x0 | button forward (g8)      |
| 0x76 |  0x0 | button forward (g8)      |
| 0x77 |  0x0 | g9                       |
| 0x78 |  0x0 | g9                       |
| 0x79 | 0x1e | g9                       |
| 0x7a |  0x0 | g10                      |
| 0x7b |  0x0 | g10                      |
| 0x7c | 0x1f | g10                      |
| 0x7d |  0x0 | g11                      |
| 0x7e |  0x0 | g11                      |
| 0x7f | 0x20 | g11                      |
| 0x80 |  0x0 | g12                      |
| 0x81 |  0x0 | g12                      |
| 0x82 | 0x21 | g12                      |
| 0x83 |  0x0 | g13                      |
| 0x84 |  0x0 | g13                      |
| 0x85 | 0x22 | g13                      |
| 0x86 |  0x0 | g14                      |
| 0x87 |  0x0 | g14                      |
| 0x88 | 0x23 | g14                      |
| 0x89 | 0x11 | g15                      |
| 0x8a |  0x0 | g15                      |
| 0x8b |  0x0 | g15                      |
| 0x8c | 0x16 | g16                      |
| 0x8d |  0x0 | g16                      |
| 0x8e |  0x0 | g16                      |
| 0x8f |  0x5 | g17                      |
| 0x90 |  0x0 | g17                      |
| 0x91 |  0x0 | g17                      |
| 0x92 | 0x12 | g18                      |
| 0x93 |  0x0 | g18                      |
| 0x94 |  0x0 | g18                      |
| 0x95 |  0x0 | g19                      |
| 0x96 |  0x0 | g19                      |
| 0x97 |  0x8 | g19                      |
| 0x98 |  0x4 | g20                      |
| 0x99 |  0x0 | g20                      |
| 0x9a |  0x0 | g20                      |
| 0x9b | 0xff |                          |
| 0x9c | 0xff |                          |
| 0x9d | 0xff |                          |
| 0x9e |  0x0 | button left              |
| 0x9f |  0x0 | button left              |
| 0xa0 |  0x0 | button left              |
| 0xa1 |  0x0 | button right             |
| 0xa2 |  0x0 | button right             |
| 0xa3 |  0x0 | button right             |
| 0xa4 |  0x0 | button middle            |
| 0xa5 |  0x0 | button middle            |
| 0xa6 |  0x0 | button middle            |
| 0xa7 |  0x0 | button horiz wheel left  |
| 0xa8 |  0x0 | button horiz wheel left  |
| 0xa9 |  0x0 | button horiz wheel left  |
| 0xaa |  0x0 | button horiz wheel right |
| 0xab |  0x0 | button horiz wheel right |
| 0xac |  0x0 | button horiz wheel right |
| 0xad |  0x0 | button side              |
| 0xae |  0x0 | button side              |
| 0xaf |  0x0 | button side              |
| 0xb0 |  0x0 | button back (g7)         |
| 0xb1 |  0x0 | button back (g7)         |
| 0xb2 |  0x0 | button back (g7)         |
| 0xb3 | 0x14 | button forward (g8)      |
| 0xb4 |  0x0 | button forward (g8)      |
| 0xb5 |  0x0 | button forward (g8)      |
| 0xb6 |  0x0 | g9                       |
| 0xb7 |  0x0 | g9                       |
| 0xb8 |  0x0 | g9                       |
| 0xb9 |  0x0 | g10                      |
| 0xba |  0x0 | g10                      |
| 0xbb |  0x0 | g10                      |
| 0xbc |  0x0 | g11                      |
| 0xbd |  0x0 | g11                      |
| 0xbe |  0x0 | g11                      |
| 0xbf |  0x0 | g12                      |
| 0xc0 |  0x0 | g12                      |
| 0xc1 |  0x0 | g12                      |
| 0xc2 |  0x0 | g13                      |
| 0xc3 |  0x0 | g13                      |
| 0xc4 |  0x0 | g13                      |
| 0xc5 |  0x0 | g14                      |
| 0xc6 |  0x0 | g14                      |
| 0xc7 |  0x0 | g14                      |
| 0xc8 |  0x0 | g15                      |
| 0xc9 |  0x0 | g15                      |
| 0xca |  0x0 | g15                      |
| 0xcb |  0x0 | g16                      |
| 0xcc |  0x0 | g16                      |
| 0xcd |  0x0 | g16                      |
| 0xce |  0x0 | g17                      |
| 0xcf |  0x0 | g17                      |
| 0xd0 |  0x0 | g17                      |
| 0xd1 |  0x0 | g18                      |
| 0xd2 |  0x0 | g18                      |
| 0xd3 |  0x0 | g18                      |
| 0xd4 |  0x0 | g19                      |
| 0xd5 |  0x0 | g19                      |
| 0xd6 |  0x0 | g19                      |
| 0xd7 |  0x0 | g20                      |
| 0xd8 |  0x0 | g20                      |
| 0xd9 |  0x0 | g20                      |

* mousecode table

|  0 | no mouse code  |
|  1 | left click     |
|  2 | right click    |
|  3 | middle click   |
|  4 | back           |
|  5 | forward        |
|  6 | ?mouse 6 event |
|  7 | ?mouse 7 event |
| 11 | dpi up         |
| 12 | dpi down       |
| 13 | dpi cycling    |
| 14 | mode switch    |
| 15 | dpi shift      |
| 16 | dpi default    |
| 17 | gshift         |


* testing
I just got things back to a somewhat sane state.

Here is the raw read:
for reportId=0x03f3, read these bytes: 
0xf3 0x00 0x00 0x00 0x02 0x06 0x00 0x00 0x00 0x00 0x00 0x00 0x1a 0x01 0x18 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x17 0x00 0x00 0x00 0x02 0x05 0x14 0x00 0x00 0x00 0x00 0x1e 0x00 0x00 0x1f 0x00 0x00 0x20 0x00 0x00 0x21 0x00 0x00 0x22 0x00 0x00 0x23 0x00 0x00 0x24 0x00 0x00 0x25 0x00 0x00 0x26 0x00 0x00 0x27 0x00 0x00 0x2d 0x00 0x00 0x2e 0x00 0xff 0xff 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x17 0x00 0x00 0x00 0x02 0x05 0x14 0x00 0x00 0x00 0x01 0x1e 0x00 0x01 0x1f 0x00 0x01 0x20 0x00 0x01 0x21 0x00 0x01 0x22 0x00 0x01 0x23 0x00 0x01 0x24 0x00 0x01 0x25 0x00 0x01 0x26 0x00 0x01 0x27 0x00 0x01 0x2d 0x00 0x01 0x2e
for reportId=0x03f4, read these bytes: 
0xf4 0xff 0xff 0xff 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x08 0x02 0x08 0x18 0x28 0x40 0x00 0x00 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x17 0x00 0x00 0x00 0x02 0x05 0x14 0x00 0x00 0x00 0x00 0x59 0x00 0x00 0x5a 0x00 0x00 0x5b 0x00 0x00 0x5c 0x00 0x00 0x5d 0x00 0x00 0x5e 0x00 0x00 0x5f 0x00 0x00 0x60 0x00 0x00 0x61 0x00 0x00 0x62 0x00 0x00 0x56 0x00 0x00 0x57 0xff 0xff 0xff 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x17 0x00 0x00 0x00 0x02 0x05 0x14 0x00 0x00 0x00 0x01 0x59 0x00 0x01 0x5a 0x00 0x01 0x5b 0x00 0x01 0x5c 0x00 0x01 0x5d 0x00 0x01 0x5e 0x00 0x01 0x5f 0x00 0x01 0x60 0x00 0x01 0x61 0x00 0x01 0x62 0x00 0x01 0x56 0x00 0x01 0x57
for reportId=0x03f5, read these bytes: 
0xf5 0x00 0xff 0x00 0x01 0x04 0x00 0x00 0x00 0x00 0x00 0x00 0x08 0x02 0x08 0x18 0x28 0x40 0x00 0x00 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x15 0x00 0x00 0x13 0x00 0x00 0x14 0x00 0x00 0x00 0x00 0x1e 0x00 0x00 0x1f 0x00 0x00 0x20 0x00 0x00 0x21 0x00 0x00 0x22 0x00 0x00 0x23 0x11 0x00 0x00 0x16 0x00 0x00 0x05 0x00 0x00 0x12 0x00 0x00 0x00 0x00 0x08 0x04 0x00 0x00 0x08 0x04 0x00 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x17 0x00 0x00 0x11 0x00 0x00 0x14 0x00 0x00 0x00 0x00 0x1e 0x00 0x14 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00

sudo ./g600prog.py -r new_defaults.json
I saved this to new_defaults.json

Now, I did a write:
sudo ./g600prog.py -w new_defaults.json -d
this:
for reportId=0x03f3, sending these bytes: 
0xf3 0x00 0x00 0x00 0x02 0x06 0x00 0x00 0x00 0x00 0x00 0x00 0x1a 0x01 0x18 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x17 0x00 0x00 0x00 0x02 0x05 0x14 0x00 0x00 0x00 0x00 0x1e 0x00 0x00 0x1f 0x00 0x00 0x20 0x00 0x00 0x21 0x00 0x00 0x22 0x00 0x00 0x23 0x00 0x00 0x24 0x00 0x00 0x25 0x00 0x00 0x26 0x00 0x00 0x27 0x00 0x00 0x2d 0x00 0x00 0x2e 0x00 0xff 0xff 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x17 0x00 0x00 0x00 0x02 0x05 0x14 0x00 0x00 0x00 0x01 0x1e 0x00 0x01 0x1f 0x00 0x01 0x20 0x00 0x01 0x21 0x00 0x01 0x22 0x00 0x01 0x23 0x00 0x01 0x24 0x00 0x01 0x25 0x00 0x01 0x26 0x00 0x01 0x27 0x00 0x01 0x2d 0x00 0x01 0x2e
for reportId=0x03f4, sending these bytes: 
0xf4 0xff 0xff 0xff 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x08 0x02 0x08 0x18 0x28 0x40 0x00 0x00 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x17 0x00 0x00 0x00 0x02 0x05 0x14 0x00 0x00 0x00 0x00 0x59 0x00 0x00 0x5a 0x00 0x00 0x5b 0x00 0x00 0x5c 0x00 0x00 0x5d 0x00 0x00 0x5e 0x00 0x00 0x5f 0x00 0x00 0x60 0x00 0x00 0x61 0x00 0x00 0x62 0x00 0x00 0x56 0x00 0x00 0x57 0xff 0xff 0xff 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x17 0x00 0x00 0x00 0x02 0x05 0x14 0x00 0x00 0x00 0x01 0x59 0x00 0x01 0x5a 0x00 0x01 0x5b 0x00 0x01 0x5c 0x00 0x01 0x5d 0x00 0x01 0x5e 0x00 0x01 0x5f 0x00 0x01 0x60 0x00 0x01 0x61 0x00 0x01 0x62 0x00 0x01 0x56 0x00 0x01 0x57
for reportId=0x03f5, sending these bytes: 
0xf5 0x00 0xff 0x00 0x01 0x04 0x00 0x00 0x00 0x00 0x00 0x00 0x08 0x02 0x08 0x18 0x28 0x40 0x00 0x00 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x15 0x00 0x00 0x13 0x00 0x00 0x14 0x00 0x00 0x00 0x00 0x1e 0x00 0x00 0x1f 0x00 0x00 0x20 0x00 0x00 0x21 0x00 0x00 0x22 0x00 0x00 0x23 0x11 0x00 0x00 0x16 0x00 0x00 0x05 0x00 0x00 0x12 0x00 0x00 0x00 0x00 0x08 0x04 0x00 0x00 0x08 0x04 0x00 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x17 0x00 0x00 0x11 0x00 0x00 0x14 0x00 0x00 0x00 0x00 0x1e 0x00 0x14 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00

A diff shows the packets being identical.
now for a debug readback:
for reportId=0x03f3, read these bytes: 
0xf3 0x00 0x00 0x00 0x02 0x06 0x00 0x00 0x00 0x00 0x00 0x00 0x08 0x02 0x08 0x18 0x28 0x40 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x17 0x00 0x00 0x00 0x02 0x05 0x14 0x00 0x00 0x00 0x00 0x1e 0x00 0x00 0x1f 0x00 0x00 0x20 0x00 0x00 0x21 0x00 0x00 0x22 0x00 0x00 0x23 0x00 0x00 0x24 0x00 0x00 0x25 0x00 0x00 0x26 0x00 0x00 0x27 0x00 0x00 0x2d 0x00 0x00 0x2e 0x00 0xff 0xff 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x17 0x00 0x00 0x00 0x02 0x05 0x14 0x00 0x00 0x00 0x01 0x1e 0x00 0x01 0x1f 0x00 0x01 0x20 0x00 0x01 0x21 0x00 0x01 0x22 0x00 0x01 0x23 0x00 0x01 0x24 0x00 0x01 0x25 0x00 0x01 0x26 0x00 0x01 0x27 0x00 0x01 0x2d 0x00 0x01 0x2e
for reportId=0x03f4, read these bytes: 
0xf4 0xff 0xff 0xff 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x08 0x02 0x08 0x18 0x28 0x40 0x00 0x00 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x17 0x00 0x00 0x00 0x02 0x05 0x14 0x00 0x00 0x00 0x00 0x59 0x00 0x00 0x5a 0x00 0x00 0x5b 0x00 0x00 0x5c 0x00 0x00 0x5d 0x00 0x00 0x5e 0x00 0x00 0x5f 0x00 0x00 0x60 0x00 0x00 0x61 0x00 0x00 0x62 0x00 0x00 0x56 0x00 0x00 0x57 0xff 0xff 0xff 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x17 0x00 0x00 0x00 0x02 0x05 0x14 0x00 0x00 0x00 0x01 0x59 0x00 0x01 0x5a 0x00 0x01 0x5b 0x00 0x01 0x5c 0x00 0x01 0x5d 0x00 0x01 0x5e 0x00 0x01 0x5f 0x00 0x01 0x60 0x00 0x01 0x61 0x00 0x01 0x62 0x00 0x01 0x56 0x00 0x01 0x57
for reportId=0x03f5, read these bytes: 
0xf5 0x00 0xff 0x00 0x01 0x04 0x00 0x00 0x00 0x00 0x00 0x00 0x08 0x02 0x08 0x18 0x28 0x40 0x00 0x00 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x15 0x00 0x00 0x00 0x00 0x02 0x05 0x14 0x00 0x00 0x00 0x00 0x1e 0x00 0x00 0x1f 0x00 0x00 0x5b 0x00 0x00 0x5c 0x00 0x00 0x5d 0x00 0x00 0x5e 0x00 0x00 0x5f 0x00 0x00 0x00 0x05 0x00 0x00 0x12 0x00 0x00 0x00 0x00 0x08 0x04 0x00 0x00 0x08 0x04 0x00 0x01 0x00 0x00 0x02 0x00 0x00 0x03 0x00 0x00 0x04 0x00 0x00 0x05 0x00 0x00 0x17 0x00 0x00 0x11 0x00 0x00 0x14 0x00 0x00 0x00 0x00 0x1e 0x00 0x14 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00

wow, its somewhat messed up.  i am not sure what happened!

** okay captured restore defaults click:
0000  c0 c0 82 83 01 88 ff ff  53 02 00 02 01 00 00 00   ........ S....... 
0010  ab 8d f2 54 00 00 00 00  1d 3b 05 00 8d ff ff ff   ...T.... .;......
0020  9a 00 00 00 9a 00 00 00  21 09 f3 03 01 00 9a 00   ........ !.......
0030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
0040  f3 00 00 00 02 06 00 00  00 00 00 00 08 02 08 18   ........ ........
0050  28 40 00 00 00 00 00 00  00 00 00 00 00 00 00 01   (@...... ........
0060  00 00 02 00 00 03 00 00  04 00 00 05 00 00 17 00   ........ ........
0070  00 00 02 05 14 00 00 00  00 1e 00 00 1f 00 00 20   ........ ....... 
0080  00 00 21 00 00 22 00 00  23 00 00 24 00 00 25 00   ..!..".. #..$..%.
0090  00 26 00 00 27 00 00 2d  00 00 2e 08 04 00 01 00   .&..'..- ........
00a0  00 02 00 00 03 00 00 04  00 00 05 00 00 17 00 00   ........ ........
00b0  00 02 05 14 00 00 00 01  1e 00 01 1f 00 01 20 00   ........ ...... .
00c0  01 21 00 01 22 00 01 23  00 01 24 00 01 25 00 01   .!.."..# ..$..%..
00d0  26 00 01 27 00 01 2d 00  01 2e                     &..'..-. ..      

0000  80 ca 82 83 01 88 ff ff  53 02 00 02 01 00 00 00   ........ S.......
0010  ac 8d f2 54 00 00 00 00  55 47 01 00 8d ff ff ff   ...T.... UG......
0020  9a 00 00 00 9a 00 00 00  21 09 f4 03 01 00 9a 00   ........ !.......
0030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
0040  f4 ff ff ff 00 00 00 00  00 00 00 00 08 02 08 18   ........ ........
0050  28 40 00 00 00 00 00 00  02 00 00 00 00 00 00 01   (@...... ........
0060  00 00 02 00 00 03 00 00  04 00 00 05 00 00 17 00   ........ ........
0070  00 00 02 05 14 00 00 00  00 59 00 00 5a 00 00 5b   ........ .Y..Z..[
0080  00 00 5c 00 00 5d 00 00  5e 00 00 5f 00 00 60 00   ..\..].. ^.._..`.
0090  00 61 00 00 62 00 00 56  00 00 57 ff ff ff 01 00   .a..b..V ..W.....
00a0  00 02 00 00 03 00 00 04  00 00 05 00 00 17 00 00   ........ ........
00b0  00 02 05 14 00 00 00 01  59 00 01 5a 00 01 5b 00   ........ Y..Z..[.
00c0  01 5c 00 01 5d 00 01 5e  00 01 5f 00 01 60 00 01   .\..]..^ .._..`..
00d0  61 00 01 62 00 01 56 00  01 57                     a..b..V. .W      

0000  c0 c3 82 83 01 88 ff ff  53 02 00 02 01 00 00 00   ........ S.......
0010  ac 8d f2 54 00 00 00 00  d4 19 0e 00 8d ff ff ff   ...T.... ........
0020  9a 00 00 00 9a 00 00 00  21 09 f5 03 01 00 9a 00   ........ !.......
0030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
0040  f5 00 ff 00 01 04 00 00  00 00 00 00 08 02 08 18   ........ ........
0050  28 40 00 00 00 00 00 00  02 00 00 00 00 00 00 01   (@...... ........
0060  00 00 02 00 00 03 00 00  04 00 00 05 00 00 15 00   ........ ........
0070  00 13 00 00 14 00 00 00  00 1e 00 00 1f 00 00 20   ........ ....... 
0080  00 00 21 00 00 22 00 00  23 11 00 00 16 00 00 05   ..!..".. #.......
0090  00 00 12 00 00 00 00 08  04 00 00 08 04 00 00 08   ........ ........
00a0  04 00 01 00 00 02 00 00  03 00 00 04 00 00 05 00   ........ ........
00b0  00 17 00 14 00 00 00 14  00 00 00 00 1e 00 14 00   ........ ........
00c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00d0  00 00 00 00 00 00 00 00  00 00                     ........ ..      

comparing...
0000  c0 c0 82 83 01 88 ff ff  53 02 00 02 01 00 00 00   ........ S....... 
0010  ab 8d f2 54 00 00 00 00  1d 3b 05 00 8d ff ff ff   ...T.... .;......
0020  9a 00 00 00 9a 00 00 00  21 09 f3 03 01 00 9a 00   ........ !.......
0030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
0040  f3 00 00 00 02 06 00 00  00 00 00 00 08 02 08 18   ........ ........
0050  28 40 00 00 00 00 00 00  00 00 00 00 00 00 00 01   (@...... ........
0060  00 00 02 00 00 03 00 00  04 00 00 05 00 00 17 00   ........ ........
0070  00 00 02 05 14 00 00 00  00 1e 00 00 1f 00 00 20   ........ ....... 
0080  00 00 21 00 00 22 00 00  23 00 00 24 00 00 25 00   ..!..".. #..$..%.
0090  00 26 00 00 27 00 00 2d  00 00 2e 08 04 00 01 00   .&..'..- ........
00a0  00 02 00 00 03 00 00 04  00 00 05 00 00 17 00 00   ........ ........
00b0  00 02 05 14 00 00 00 01  1e 00 01 1f 00 01 20 00   ........ ...... .
00c0  01 21 00 01 22 00 01 23  00 01 24 00 01 25 00 01   .!.."..# ..$..%..
00d0  26 00 01 27 00 01 2d 00  01 2e                     &..'..-. ..      

      f3 00 00 00 02 06 00 00  00 00 00 00 08 02 08 18
      28 40 00 00 00 00 00 00  00 00 00 00 00 00 00 01
      00 00 02 00 00 03 00 00  04 00 00 05 00 00 17 00
      00 00 02 05 14 00 00 00  00 1e 00 00 1f 00 00 20
      00 00 21 00 00 22 00 00  23 00 00 24 00 00 25 00
      00 26 00 00 27 00 00 2d  00 00 2e 08 04 00 01 00
      00 02 00 00 03 00 00 04  00 00 05 00 00 17 00 00
      00 02 05 14 00 00 00 01  1e 00 01 1f 00 01 20 00
      01 21 00 01 22 00 01 23  00 01 24 00 01 25 00 01
      26 00 01 27 00 01 2d 00  01 2e

